Add contributing guidelines for the project
paritytech/substrate-connect pull request #184
Opened 2021-03-23 12:47 UTC by raoulmillais

Add a guide explaining how to make a good pull request that can be reviewed and merged quickly with some tips on testing and writing descriptions.

2021-03-23 15:30 UTC, goldsteinsveta approved these changes

2021-03-23 15:40 UTC, wirednkod commented
I would add the "documentation" part that is missing (keep notes/documentation inline with the code if possible - not only in PR logs/commments)

2021-03-23 15:40 UTC, wirednkod requested changes
I would add the "documentation" part that is missing (keep notes/documentation inline with the code if possible - not only in PR logs/commments)

2021-03-24 14:04 UTC, raoulmillais commented
I al

> I would add the "documentation" part that is missing (keep notes/documentation inline with the code if possible - not only in PR logs/commments)

I did have  a note on that in the tips section at the bottom.  I've elaborated a bit

2021-03-25 08:25 UTC, wirednkod approved these changes

2021-03-25 08:28 UTC, merged