Refactor health checks in the extension
paritytech/substrate-connect pull request #858
Opened 2022-03-10 13:02 UTC by tomaka

Fix https://github.com/paritytech/substrate-connect/issues/741

This PR can be more easily reviewed commit by commit.

This PR removes all health-checking-related code from `ConnectionManager` and adds a new `ConnectionManagerWithHealth` class that builds on top of `ConnectionManager` and adds the health checks.
This simplifies the logic by a lot by removing many callbacks and thus ambiguities in the order of events.

In addition, these new health checks don't use the `HealthChecker`, but instead are reimplemented from scratch and use the new `chainHead_unstable_follow` JSON-RPC function.
While using an unstable function is risky, considering that we update smoldot versions manually, we will detect if smoldot breaks this function and we didn't update this code.

2022-03-10 16:31 UTC, wirednkod requested changes

2022-03-10 17:02 UTC, tomaka commented on projects/extension/src/background/ConnectionManagerWithHealth.ts
> +      for (const [chainId, _] of sandbox) {
Yeah I really find that a bit stupid. I would like to make it clear by reading the code that this is a tuple of two elements, but I guess there's no way to do that and make the lint happy at the same time.

2022-03-11 09:15 UTC, wirednkod approved these changes

2022-03-11 12:42 UTC, tomaka commented
Ideally we'd wait for @josepot to take a look, but I think it's fine to merge now

2022-03-11 12:48 UTC, merged